title: Regression Analysis

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

minima:
  skin: dark

header_pages: []

kramdown:
  input: GFM

titles_from_headings:
  enabled: true
  strip_title: true